### ISSUE TITLE
Need add a IR receiver to sync state while using remote.

### ISSUE THREAD

**Issue by LuuTinhIT** [curla92/Daikin-AC-Homekit#2]
Hi,
Can you include funtion to receiving IR commands while using remote?
Please refer this example: https://github.com/maximkulkin/esp-ir-thermostat/blob/master/main/main.c
Thank you so much :)

**Comment by GPL71** [comment]
@curla92 very interesting this feautere

**Comment by curla92** [comment]
i'm using a different library, i ll think about it
